language: julia
os:
  - linux
  - osx
julia:
  - 0.6
notifications:
  email: false
#script:
#  - julia --check-bounds=yes --code-coverage -e 'Pkg.clone(pwd()); Pkg.test("Whippet", coverage=true)'
after_success:
  - julia -e 'Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
